//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.16 at 01:29:12 PM KST 
//


package com.ictway.wisesphere.services.jaxb.wms;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SupportedVersions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Version" type="{http://www.deegree.org/services/wms}WMSVersionType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MetadataStoreId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MetadataURLTemplate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ServiceConfiguration" type="{http://www.deegree.org/services/wms}ServiceConfigurationType"/>
 *         &lt;element name="FeatureInfoFormats" type="{http://www.deegree.org/services/wms}FeatureInfoFormatsType" minOccurs="0"/>
 *         &lt;element name="ExtendedCapabilities" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any processContents='lax'/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LayerLimit" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="MaxWidth" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="MaxHeight" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="configVersion" use="required" type="{http://www.deegree.org/services/wms}ConfigVersionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "supportedVersions",
    "metadataStoreId",
    "metadataURLTemplate",
    "serviceConfiguration",
    "featureInfoFormats",
    "extendedCapabilities",
    "layerLimit",
    "maxWidth",
    "maxHeight"
})
@XmlRootElement(name = "deegreeWMS")
//@XmlRootElement(name = "spatiumWMS") // BY_JIN
public class DeegreeWMS {

    @XmlElement(name = "SupportedVersions")
    protected DeegreeWMS.SupportedVersions supportedVersions;
    @XmlElement(name = "MetadataStoreId")
    protected String metadataStoreId;
    @XmlElement(name = "MetadataURLTemplate")
    protected String metadataURLTemplate;
    @XmlElement(name = "ServiceConfiguration", required = true)
    protected ServiceConfigurationType serviceConfiguration;
    @XmlElement(name = "FeatureInfoFormats")
    protected FeatureInfoFormatsType featureInfoFormats;
    @XmlElement(name = "ExtendedCapabilities")
    protected List<DeegreeWMS.ExtendedCapabilities> extendedCapabilities;
    @XmlElement(name = "LayerLimit")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger layerLimit;
    @XmlElement(name = "MaxWidth")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxWidth;
    @XmlElement(name = "MaxHeight")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxHeight;
    @XmlAttribute(name = "configVersion", required = true)
    protected String configVersion;

    /**
     * Gets the value of the supportedVersions property.
     * 
     * @return
     *     possible object is
     *     {@link DeegreeWMS.SupportedVersions }
     *     
     */
    public DeegreeWMS.SupportedVersions getSupportedVersions() {
        return supportedVersions;
    }

    /**
     * Sets the value of the supportedVersions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeegreeWMS.SupportedVersions }
     *     
     */
    public void setSupportedVersions(DeegreeWMS.SupportedVersions value) {
        this.supportedVersions = value;
    }

    /**
     * Gets the value of the metadataStoreId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadataStoreId() {
        return metadataStoreId;
    }

    /**
     * Sets the value of the metadataStoreId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadataStoreId(String value) {
        this.metadataStoreId = value;
    }

    /**
     * Gets the value of the metadataURLTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadataURLTemplate() {
        return metadataURLTemplate;
    }

    /**
     * Sets the value of the metadataURLTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadataURLTemplate(String value) {
        this.metadataURLTemplate = value;
    }

    /**
     * Gets the value of the serviceConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceConfigurationType }
     *     
     */
    public ServiceConfigurationType getServiceConfiguration() {
        return serviceConfiguration;
    }

    /**
     * Sets the value of the serviceConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceConfigurationType }
     *     
     */
    public void setServiceConfiguration(ServiceConfigurationType value) {
        this.serviceConfiguration = value;
    }

    /**
     * Gets the value of the featureInfoFormats property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureInfoFormatsType }
     *     
     */
    public FeatureInfoFormatsType getFeatureInfoFormats() {
        return featureInfoFormats;
    }

    /**
     * Sets the value of the featureInfoFormats property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureInfoFormatsType }
     *     
     */
    public void setFeatureInfoFormats(FeatureInfoFormatsType value) {
        this.featureInfoFormats = value;
    }

    /**
     * Gets the value of the extendedCapabilities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extendedCapabilities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtendedCapabilities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeegreeWMS.ExtendedCapabilities }
     * 
     * 
     */
    public List<DeegreeWMS.ExtendedCapabilities> getExtendedCapabilities() {
        if (extendedCapabilities == null) {
            extendedCapabilities = new ArrayList<DeegreeWMS.ExtendedCapabilities>();
        }
        return this.extendedCapabilities;
    }

    /**
     * Gets the value of the layerLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLayerLimit() {
        return layerLimit;
    }

    /**
     * Sets the value of the layerLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLayerLimit(BigInteger value) {
        this.layerLimit = value;
    }

    /**
     * Gets the value of the maxWidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxWidth() {
        return maxWidth;
    }

    /**
     * Sets the value of the maxWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxWidth(BigInteger value) {
        this.maxWidth = value;
    }

    /**
     * Gets the value of the maxHeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxHeight() {
        return maxHeight;
    }

    /**
     * Sets the value of the maxHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxHeight(BigInteger value) {
        this.maxHeight = value;
    }

    /**
     * Gets the value of the configVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigVersion() {
        return configVersion;
    }

    /**
     * Sets the value of the configVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigVersion(String value) {
        this.configVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any processContents='lax'/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "any"
    })
    public static class ExtendedCapabilities {

        @XmlAnyElement
        protected Element any;

        /**
         * Gets the value of the any property.
         * 
         * @return
         *     possible object is
         *     {@link Element }
         *     
         */
        public Element getAny() {
            return any;
        }

        /**
         * Sets the value of the any property.
         * 
         * @param value
         *     allowed object is
         *     {@link Element }
         *     
         */
        public void setAny(Element value) {
            this.any = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Version" type="{http://www.deegree.org/services/wms}WMSVersionType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "version"
    })
    public static class SupportedVersions {

        @XmlElement(name = "Version", required = true)
        protected List<String> version;

        /**
         * Gets the value of the version property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the version property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVersion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getVersion() {
            if (version == null) {
                version = new ArrayList<String>();
            }
            return this.version;
        }

    }

}
