//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.16 at 01:29:12 PM KST 
//


package com.ictway.wisesphere.services.jaxb.wms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/services/wms}BaseAbstractLayerType">
 *       &lt;choice>
 *         &lt;element name="ShapefileDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PostGIS">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="schema" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "shapefileDirectory",
    "postGIS"
})
public class DynamicLayer
    extends BaseAbstractLayerType
{

    @XmlElement(name = "ShapefileDirectory")
    protected String shapefileDirectory;
    @XmlElement(name = "PostGIS")
    protected DynamicLayer.PostGIS postGIS;

    /**
     * Gets the value of the shapefileDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShapefileDirectory() {
        return shapefileDirectory;
    }

    /**
     * Sets the value of the shapefileDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShapefileDirectory(String value) {
        this.shapefileDirectory = value;
    }

    /**
     * Gets the value of the postGIS property.
     * 
     * @return
     *     possible object is
     *     {@link DynamicLayer.PostGIS }
     *     
     */
    public DynamicLayer.PostGIS getPostGIS() {
        return postGIS;
    }

    /**
     * Sets the value of the postGIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link DynamicLayer.PostGIS }
     *     
     */
    public void setPostGIS(DynamicLayer.PostGIS value) {
        this.postGIS = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="schema" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PostGIS {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "schema")
        protected String schema;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the schema property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSchema() {
            return schema;
        }

        /**
         * Sets the value of the schema property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSchema(String value) {
            this.schema = value;
        }

    }

}
