//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.16 at 01:29:12 PM KST 
//


package com.ictway.wisesphere.services.jaxb.wms;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for FeatureInfoFormatsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeatureInfoFormatsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GetFeatureInfoFormat" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice>
 *                     &lt;element name="File" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="XSLTFile">
 *                       &lt;complexType>
 *                         &lt;simpleContent>
 *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                             &lt;attribute name="gmlVersion" type="{http://www.deegree.org/services/wms}GMLVersionType" default="GML_32" />
 *                           &lt;/extension>
 *                         &lt;/simpleContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/choice>
 *                   &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeatureInfoFormatsType", propOrder = {
    "getFeatureInfoFormat"
})
public class FeatureInfoFormatsType {

    @XmlElement(name = "GetFeatureInfoFormat")
    protected List<FeatureInfoFormatsType.GetFeatureInfoFormat> getFeatureInfoFormat;

    /**
     * Gets the value of the getFeatureInfoFormat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the getFeatureInfoFormat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGetFeatureInfoFormat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureInfoFormatsType.GetFeatureInfoFormat }
     * 
     * 
     */
    public List<FeatureInfoFormatsType.GetFeatureInfoFormat> getGetFeatureInfoFormat() {
        if (getFeatureInfoFormat == null) {
            getFeatureInfoFormat = new ArrayList<FeatureInfoFormatsType.GetFeatureInfoFormat>();
        }
        return this.getFeatureInfoFormat;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="File" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *           &lt;element name="XSLTFile">
     *             &lt;complexType>
     *               &lt;simpleContent>
     *                 &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                   &lt;attribute name="gmlVersion" type="{http://www.deegree.org/services/wms}GMLVersionType" default="GML_32" />
     *                 &lt;/extension>
     *               &lt;/simpleContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/choice>
     *         &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "file",
        "xsltFile",
        "format"
    })
    public static class GetFeatureInfoFormat {

        @XmlElement(name = "File")
        protected String file;
        @XmlElement(name = "XSLTFile")
        protected FeatureInfoFormatsType.GetFeatureInfoFormat.XSLTFile xsltFile;
        @XmlElement(name = "Format", required = true)
        protected String format;

        /**
         * Gets the value of the file property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFile() {
            return file;
        }

        /**
         * Sets the value of the file property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFile(String value) {
            this.file = value;
        }

        /**
         * Gets the value of the xsltFile property.
         * 
         * @return
         *     possible object is
         *     {@link FeatureInfoFormatsType.GetFeatureInfoFormat.XSLTFile }
         *     
         */
        public FeatureInfoFormatsType.GetFeatureInfoFormat.XSLTFile getXSLTFile() {
            return xsltFile;
        }

        /**
         * Sets the value of the xsltFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link FeatureInfoFormatsType.GetFeatureInfoFormat.XSLTFile }
         *     
         */
        public void setXSLTFile(FeatureInfoFormatsType.GetFeatureInfoFormat.XSLTFile value) {
            this.xsltFile = value;
        }

        /**
         * Gets the value of the format property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormat() {
            return format;
        }

        /**
         * Sets the value of the format property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormat(String value) {
            this.format = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="gmlVersion" type="{http://www.deegree.org/services/wms}GMLVersionType" default="GML_32" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class XSLTFile {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "gmlVersion")
            protected GMLVersionType gmlVersion;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the gmlVersion property.
             * 
             * @return
             *     possible object is
             *     {@link GMLVersionType }
             *     
             */
            public GMLVersionType getGmlVersion() {
                if (gmlVersion == null) {
                    return GMLVersionType.GML_32;
                } else {
                    return gmlVersion;
                }
            }

            /**
             * Sets the value of the gmlVersion property.
             * 
             * @param value
             *     allowed object is
             *     {@link GMLVersionType }
             *     
             */
            public void setGmlVersion(GMLVersionType value) {
                this.gmlVersion = value;
            }

        }

    }

}
