//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.16 at 01:29:12 PM KST 
//


package com.ictway.wisesphere.services.jaxb.wms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LayerOptionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LayerOptionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AntiAliasing" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RenderingQuality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Interpolation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaxFeatures" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="FeatureInfoRadius" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LayerOptionsType", propOrder = {
    "antiAliasing",
    "renderingQuality",
    "interpolation",
    "maxFeatures",
    "featureInfoRadius"
})
public class LayerOptionsType {

    @XmlElement(name = "AntiAliasing")
    protected String antiAliasing;
    @XmlElement(name = "RenderingQuality")
    protected String renderingQuality;
    @XmlElement(name = "Interpolation")
    protected String interpolation;
    @XmlElement(name = "MaxFeatures")
    protected Integer maxFeatures;
    @XmlElement(name = "FeatureInfoRadius")
    protected Integer featureInfoRadius;

    /**
     * Gets the value of the antiAliasing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAntiAliasing() {
        return antiAliasing;
    }

    /**
     * Sets the value of the antiAliasing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAntiAliasing(String value) {
        this.antiAliasing = value;
    }

    /**
     * Gets the value of the renderingQuality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRenderingQuality() {
        return renderingQuality;
    }

    /**
     * Sets the value of the renderingQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenderingQuality(String value) {
        this.renderingQuality = value;
    }

    /**
     * Gets the value of the interpolation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterpolation() {
        return interpolation;
    }

    /**
     * Sets the value of the interpolation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterpolation(String value) {
        this.interpolation = value;
    }

    /**
     * Gets the value of the maxFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxFeatures() {
        return maxFeatures;
    }

    /**
     * Sets the value of the maxFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxFeatures(Integer value) {
        this.maxFeatures = value;
    }

    /**
     * Gets the value of the featureInfoRadius property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFeatureInfoRadius() {
        return featureInfoRadius;
    }

    /**
     * Sets the value of the featureInfoRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFeatureInfoRadius(Integer value) {
        this.featureInfoRadius = value;
    }

}
