//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.16 at 01:29:12 PM KST 
//


package com.ictway.wisesphere.services.jaxb.wms;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ictway.spatium.services.jaxb.wms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Keywords_QNAME = new QName("http://www.deegree.org/services/wms", "Keywords");
    private final static QName _RequestableLayer_QNAME = new QName("http://www.deegree.org/services/wms", "RequestableLayer");
    private final static QName _UnrequestableLayer_QNAME = new QName("http://www.deegree.org/services/wms", "UnrequestableLayer");
    private final static QName _BoundingBox_QNAME = new QName("http://www.deegree.org/services/wms", "BoundingBox");
    private final static QName _LogicalLayer_QNAME = new QName("http://www.deegree.org/services/wms", "LogicalLayer");
    private final static QName _DynamicLayer_QNAME = new QName("http://www.deegree.org/services/wms", "DynamicLayer");
    private final static QName _StatisticsLayer_QNAME = new QName("http://www.deegree.org/services/wms", "StatisticsLayer");
    private final static QName _ScaleDenominators_QNAME = new QName("http://www.deegree.org/services/wms", "ScaleDenominators");
    private final static QName _AbstractLayer_QNAME = new QName("http://www.deegree.org/services/wms", "AbstractLayer");
    private final static QName _SLDStyleTypeLegendConfigurationFile_QNAME = new QName("http://www.deegree.org/services/wms", "LegendConfigurationFile");
    private final static QName _SLDStyleTypeUserStyle_QNAME = new QName("http://www.deegree.org/services/wms", "UserStyle");
    private final static QName _SLDStyleTypeName_QNAME = new QName("http://www.deegree.org/services/wms", "Name");
    private final static QName _SLDStyleTypeLegendGraphicFile_QNAME = new QName("http://www.deegree.org/services/wms", "LegendGraphicFile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ictway.spatium.services.jaxb.wms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeegreeWMS }
     * 
     */
    public DeegreeWMS createDeegreeWMS() {
        return new DeegreeWMS();
    }

    /**
     * Create an instance of {@link SLDStyleType }
     * 
     */
    public SLDStyleType createSLDStyleType() {
        return new SLDStyleType();
    }

    /**
     * Create an instance of {@link DirectStyleType }
     * 
     */
    public DirectStyleType createDirectStyleType() {
        return new DirectStyleType();
    }

    /**
     * Create an instance of {@link DynamicLayer }
     * 
     */
    public DynamicLayer createDynamicLayer() {
        return new DynamicLayer();
    }

    /**
     * Create an instance of {@link FeatureInfoFormatsType }
     * 
     */
    public FeatureInfoFormatsType createFeatureInfoFormatsType() {
        return new FeatureInfoFormatsType();
    }

    /**
     * Create an instance of {@link FeatureInfoFormatsType.GetFeatureInfoFormat }
     * 
     */
    public FeatureInfoFormatsType.GetFeatureInfoFormat createFeatureInfoFormatsTypeGetFeatureInfoFormat() {
        return new FeatureInfoFormatsType.GetFeatureInfoFormat();
    }

    /**
     * Create an instance of {@link DeegreeWMS.SupportedVersions }
     * 
     */
    public DeegreeWMS.SupportedVersions createDeegreeWMSSupportedVersions() {
        return new DeegreeWMS.SupportedVersions();
    }

    /**
     * Create an instance of {@link ServiceConfigurationType }
     * 
     */
    public ServiceConfigurationType createServiceConfigurationType() {
        return new ServiceConfigurationType();
    }

    /**
     * Create an instance of {@link DeegreeWMS.ExtendedCapabilities }
     * 
     */
    public DeegreeWMS.ExtendedCapabilities createDeegreeWMSExtendedCapabilities() {
        return new DeegreeWMS.ExtendedCapabilities();
    }

    /**
     * Create an instance of {@link ScaleDenominatorsType }
     * 
     */
    public ScaleDenominatorsType createScaleDenominatorsType() {
        return new ScaleDenominatorsType();
    }

    /**
     * Create an instance of {@link BaseAbstractLayerType }
     * 
     */
    public BaseAbstractLayerType createBaseAbstractLayerType() {
        return new BaseAbstractLayerType();
    }

    /**
     * Create an instance of {@link StatisticsLayer }
     * 
     */
    public StatisticsLayer createStatisticsLayer() {
        return new StatisticsLayer();
    }

    /**
     * Create an instance of {@link LogicalLayer }
     * 
     */
    public LogicalLayer createLogicalLayer() {
        return new LogicalLayer();
    }

    /**
     * Create an instance of {@link BoundingBoxType }
     * 
     */
    public BoundingBoxType createBoundingBoxType() {
        return new BoundingBoxType();
    }

    /**
     * Create an instance of {@link UnrequestableLayer }
     * 
     */
    public UnrequestableLayer createUnrequestableLayer() {
        return new UnrequestableLayer();
    }

    /**
     * Create an instance of {@link RequestableLayer }
     * 
     */
    public RequestableLayer createRequestableLayer() {
        return new RequestableLayer();
    }

    /**
     * Create an instance of {@link KeywordsType }
     * 
     */
    public KeywordsType createKeywordsType() {
        return new KeywordsType();
    }

    /**
     * Create an instance of {@link LanguageStringType }
     * 
     */
    public LanguageStringType createLanguageStringType() {
        return new LanguageStringType();
    }

    /**
     * Create an instance of {@link LayerOptionsType }
     * 
     */
    public LayerOptionsType createLayerOptionsType() {
        return new LayerOptionsType();
    }

    /**
     * Create an instance of {@link DimensionType }
     * 
     */
    public DimensionType createDimensionType() {
        return new DimensionType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link AbstractLayerType }
     * 
     */
    public AbstractLayerType createAbstractLayerType() {
        return new AbstractLayerType();
    }

    /**
     * Create an instance of {@link SLDStyleType.LegendGraphicFile }
     * 
     */
    public SLDStyleType.LegendGraphicFile createSLDStyleTypeLegendGraphicFile() {
        return new SLDStyleType.LegendGraphicFile();
    }

    /**
     * Create an instance of {@link DirectStyleType.LegendGraphicFile }
     * 
     */
    public DirectStyleType.LegendGraphicFile createDirectStyleTypeLegendGraphicFile() {
        return new DirectStyleType.LegendGraphicFile();
    }

    /**
     * Create an instance of {@link DynamicLayer.PostGIS }
     * 
     */
    public DynamicLayer.PostGIS createDynamicLayerPostGIS() {
        return new DynamicLayer.PostGIS();
    }

    /**
     * Create an instance of {@link FeatureInfoFormatsType.GetFeatureInfoFormat.XSLTFile }
     * 
     */
    public FeatureInfoFormatsType.GetFeatureInfoFormat.XSLTFile createFeatureInfoFormatsTypeGetFeatureInfoFormatXSLTFile() {
        return new FeatureInfoFormatsType.GetFeatureInfoFormat.XSLTFile();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeywordsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/services/wms", name = "Keywords")
    public JAXBElement<KeywordsType> createKeywords(KeywordsType value) {
        return new JAXBElement<KeywordsType>(_Keywords_QNAME, KeywordsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestableLayer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/services/wms", name = "RequestableLayer", substitutionHeadNamespace = "http://www.deegree.org/services/wms", substitutionHeadName = "AbstractLayer")
    public JAXBElement<RequestableLayer> createRequestableLayer(RequestableLayer value) {
        return new JAXBElement<RequestableLayer>(_RequestableLayer_QNAME, RequestableLayer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnrequestableLayer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/services/wms", name = "UnrequestableLayer", substitutionHeadNamespace = "http://www.deegree.org/services/wms", substitutionHeadName = "AbstractLayer")
    public JAXBElement<UnrequestableLayer> createUnrequestableLayer(UnrequestableLayer value) {
        return new JAXBElement<UnrequestableLayer>(_UnrequestableLayer_QNAME, UnrequestableLayer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BoundingBoxType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/services/wms", name = "BoundingBox")
    public JAXBElement<BoundingBoxType> createBoundingBox(BoundingBoxType value) {
        return new JAXBElement<BoundingBoxType>(_BoundingBox_QNAME, BoundingBoxType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogicalLayer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/services/wms", name = "LogicalLayer", substitutionHeadNamespace = "http://www.deegree.org/services/wms", substitutionHeadName = "AbstractLayer")
    public JAXBElement<LogicalLayer> createLogicalLayer(LogicalLayer value) {
        return new JAXBElement<LogicalLayer>(_LogicalLayer_QNAME, LogicalLayer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DynamicLayer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/services/wms", name = "DynamicLayer", substitutionHeadNamespace = "http://www.deegree.org/services/wms", substitutionHeadName = "AbstractLayer")
    public JAXBElement<DynamicLayer> createDynamicLayer(DynamicLayer value) {
        return new JAXBElement<DynamicLayer>(_DynamicLayer_QNAME, DynamicLayer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatisticsLayer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/services/wms", name = "StatisticsLayer", substitutionHeadNamespace = "http://www.deegree.org/services/wms", substitutionHeadName = "AbstractLayer")
    public JAXBElement<StatisticsLayer> createStatisticsLayer(StatisticsLayer value) {
        return new JAXBElement<StatisticsLayer>(_StatisticsLayer_QNAME, StatisticsLayer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScaleDenominatorsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/services/wms", name = "ScaleDenominators")
    public JAXBElement<ScaleDenominatorsType> createScaleDenominators(ScaleDenominatorsType value) {
        return new JAXBElement<ScaleDenominatorsType>(_ScaleDenominators_QNAME, ScaleDenominatorsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseAbstractLayerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/services/wms", name = "AbstractLayer")
    public JAXBElement<BaseAbstractLayerType> createAbstractLayer(BaseAbstractLayerType value) {
        return new JAXBElement<BaseAbstractLayerType>(_AbstractLayer_QNAME, BaseAbstractLayerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/services/wms", name = "LegendConfigurationFile", scope = SLDStyleType.class)
    public JAXBElement<String> createSLDStyleTypeLegendConfigurationFile(String value) {
        return new JAXBElement<String>(_SLDStyleTypeLegendConfigurationFile_QNAME, String.class, SLDStyleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/services/wms", name = "UserStyle", scope = SLDStyleType.class)
    public JAXBElement<String> createSLDStyleTypeUserStyle(String value) {
        return new JAXBElement<String>(_SLDStyleTypeUserStyle_QNAME, String.class, SLDStyleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/services/wms", name = "Name", scope = SLDStyleType.class)
    public JAXBElement<String> createSLDStyleTypeName(String value) {
        return new JAXBElement<String>(_SLDStyleTypeName_QNAME, String.class, SLDStyleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SLDStyleType.LegendGraphicFile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/services/wms", name = "LegendGraphicFile", scope = SLDStyleType.class)
    public JAXBElement<SLDStyleType.LegendGraphicFile> createSLDStyleTypeLegendGraphicFile(SLDStyleType.LegendGraphicFile value) {
        return new JAXBElement<SLDStyleType.LegendGraphicFile>(_SLDStyleTypeLegendGraphicFile_QNAME, SLDStyleType.LegendGraphicFile.class, SLDStyleType.class, value);
    }

}
