//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.16 at 01:29:12 PM KST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.deegree.org/services/wms", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ictway.wisesphere.services.jaxb.wms;
