//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.16 at 01:29:12 PM KST 
//


package com.ictway.wisesphere.services.jaxb.wms;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for SLDStyleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SLDStyleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="File" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NamedLayer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *           &lt;element name="UserStyle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;choice minOccurs="0">
 *             &lt;element name="LegendConfigurationFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *             &lt;element name="LegendGraphicFile">
 *               &lt;complexType>
 *                 &lt;simpleContent>
 *                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                     &lt;attribute name="outputGetLegendGraphicUrl" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *                   &lt;/extension>
 *                 &lt;/simpleContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SLDStyleType", propOrder = {
    "file",
    "namedLayer",
    "nameAndUserStyleAndLegendConfigurationFile"
})
public class SLDStyleType {

    @XmlElement(name = "File", required = true)
    protected String file;
    @XmlElement(name = "NamedLayer", required = true)
    protected String namedLayer;
    @XmlElementRefs({
        @XmlElementRef(name = "Name", namespace = "http://www.deegree.org/services/wms", type = JAXBElement.class),
        @XmlElementRef(name = "UserStyle", namespace = "http://www.deegree.org/services/wms", type = JAXBElement.class),
        @XmlElementRef(name = "LegendGraphicFile", namespace = "http://www.deegree.org/services/wms", type = JAXBElement.class),
        @XmlElementRef(name = "LegendConfigurationFile", namespace = "http://www.deegree.org/services/wms", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> nameAndUserStyleAndLegendConfigurationFile;

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFile(String value) {
        this.file = value;
    }

    /**
     * Gets the value of the namedLayer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamedLayer() {
        return namedLayer;
    }

    /**
     * Sets the value of the namedLayer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamedLayer(String value) {
        this.namedLayer = value;
    }

    /**
     * Gets the value of the nameAndUserStyleAndLegendConfigurationFile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameAndUserStyleAndLegendConfigurationFile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameAndUserStyleAndLegendConfigurationFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link SLDStyleType.LegendGraphicFile }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getNameAndUserStyleAndLegendConfigurationFile() {
        if (nameAndUserStyleAndLegendConfigurationFile == null) {
            nameAndUserStyleAndLegendConfigurationFile = new ArrayList<JAXBElement<?>>();
        }
        return this.nameAndUserStyleAndLegendConfigurationFile;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="outputGetLegendGraphicUrl" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class LegendGraphicFile {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "outputGetLegendGraphicUrl")
        protected Boolean outputGetLegendGraphicUrl;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the outputGetLegendGraphicUrl property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isOutputGetLegendGraphicUrl() {
            if (outputGetLegendGraphicUrl == null) {
                return true;
            } else {
                return outputGetLegendGraphicUrl;
            }
        }

        /**
         * Sets the value of the outputGetLegendGraphicUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setOutputGetLegendGraphicUrl(Boolean value) {
            this.outputGetLegendGraphicUrl = value;
        }

    }

}
