//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.16 at 01:29:12 PM KST 
//


package com.ictway.wisesphere.services.jaxb.wms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.deegree.org/services/wms}AbstractLayerType">
 *       &lt;sequence>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Abstract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/services/wms}Keywords" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/services/wms}BoundingBox" minOccurs="0"/>
 *         &lt;element name="CRS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.deegree.org/services/wms}ScaleDenominators" minOccurs="0"/>
 *           &lt;element name="ScaleUntil" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *           &lt;element name="ScaleAbove" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.deegree.org/services/wms}AbstractLayer" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="FeatureStoreId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="CoverageStoreId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="RemoteWMSStoreId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *         &lt;element name="DirectStyle" type="{http://www.deegree.org/services/wms}DirectStyleType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SLDStyle" type="{http://www.deegree.org/services/wms}SLDStyleType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LayerOptions" type="{http://www.deegree.org/services/wms}LayerOptionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="queryable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class UnrequestableLayer
    extends AbstractLayerType
{


}
